name: CI

on:
  push:
    branches:
      - main
      - feature/shopping-list

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Server Docker Image
        run: docker build -t shopping-server ./server

      - name: Build Client Docker Image
        run: docker build -t shopping-client ./client


